# 线性回归 {#lm}

线性模型是数据分析中最常用的一种分析方法。最基础的往往最深刻。

```{r message = FALSE, warning = FALSE}
library(tidyverse)
```


## 四个前提
线性回归需要满足四个前提假设：

1. **Linearity **
    - 因变量和每个自变量都是线性关系

2. **Indpendence **
    - 对于所有的观测值，它们的误差项相互之间是独立的

3. **Normality **
    - 误差项服从正态分布

4. **Equal-variance **  
    - [所有的误差项具有同样方差](<https://www.zhihu.com/question/67473778>)

这四个假设的首字母，合起来就是LINE，这样很好记

## 案例
```{r}
library(rethinking)
data(Howell1)
d <- Howell1
```


```{r}
rm(Howell1)
detach(package:rethinking, unload = T)
library(brms)
```



```{r}
d2 <-
  d %>%
  filter(age >= 18)
```



```{r}
ggplot(
  data = d2,
  aes(x = weight, y = height)
) +
  geom_point(shape = 1, size = 2) +
  theme_bw() +
  theme(panel.grid = element_blank())
```


## 先验概率

```{r}
# prior for mu $\text{Normal}(178, 100)$
p1 <- ggplot(
  data = tibble(x = seq(from = 100, to = 250, by = .1)),
  aes(x = x, y = dnorm(x, mean = 178, sd = 20))
) +
  geom_line() +
  ylab("density")



# prior for beta $\text{Normal}(0, 10)$
p2 <- tibble(beta = -40:40) %>%
  mutate(density = dnorm(beta, mean = 0, sd = 10)) %>%
  ggplot(aes(x = beta, ymin = 0, ymax = density)) +
  geom_ribbon(size = 0, fill = "royalblue") +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(expression(beta)) +
  theme(panel.grid = element_blank())


# prior for sigma $\text{Uniform}(0, 50)$
p3 <- tibble(x = seq(from = -10, to = 60, by = .1)) %>%

  ggplot(aes(x = x, y = dunif(x, min = 0, max = 50))) +
  geom_line() +
  scale_y_continuous(NULL, breaks = NULL) +
  theme(panel.grid = element_blank())

library(patchwork)
p1 + p2 + p3
```

## 模型

## 使用stan
```{r}
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
Sys.setenv(LOCAL_CPPFLAGS = "-march=native")
```

```{r}
tb <- tibble(
	weight = c(64, 68, 72)
)




# put into a list
stan_dat <- list(
	N = nrow(d2),
	x = d2$weight,
	y = d2$height,
	M = nrow(tb),
	new_x = tb$weight
)




fit <- stan(file = "./models/simple.stan", 
			data = stan_dat,
			iter = 41000, 
			chains = 4, 
			warmup = 40000, 
			cores = 4)
```

```{r}
stan_trace(fit)
```


```{r, eval=FALSE}
# fit
plot(fit)
plot(fit, pars = c("alpha", "beta"))
stan_trace(fit)
stan_plot(fit, pars = c("alpha", "beta"))
stan_hist(fit, pars = c("alpha", "beta"))
stan_dens(fit, pars = c("alpha", "beta"))
get_posterior_mean(fit)
as.data.frame(fit) %>% as_tibble()
```

```{r, eval=FALSE}
fit %>% tidybayes::spread_draws(alpha, beta)

fit %>% tidybayes::spread_draws(new_y[n]) 
fit %>% tidybayes::spread_draws(new_y[weight]) 
fit %>% tidybayes::spread_draws(new_y[condition]) 

fit %>% tidybayes::spread_draws(new_y[i]) %>% 
	median_qi()
```


```{r, eval=FALSE}
fit %>%
	spread_draws(beta) %>%
	ggplot(aes(y = 0, x = beta, fill = stat(x > .85))) +
	stat_halfeyeh() +
	geom_vline(xintercept = .85, linetype = "dashed") +
	scale_fill_manual(values = c("gray80", "skyblue"))
```



```{r}
library(tidybayes)
# stanfit模型不能用add_predicted_draws(fit)， 很遗憾
# 只有先写在.stan文件里
post_draw1 <- fit %>% tidybayes::spread_draws(new_y[condition]) 
post_draw1
```


```{r}
prob_pred1 <- post_draw1 %>% 
	group_by(condition) %>% 
	summarise(
		pred_height_mean = mean(new_y),
		prob_above_line = mean(new_y >= 170)
	)
prob_pred1
```


```{r}
post_draw1 %>% 
	ggplot(aes(x = new_y, y = factor(condition), fill = stat(x > 170))) +
	stat_halfeyeh() +
	geom_vline(xintercept = 170, linetype = "dashed", size = 2,
			   color = "red") +
	scale_fill_manual(values = c("gray80", "skyblue")) +
	scale_x_continuous(limits = c(150, 200)) 
```

```{r}
post_draw1 %>% 
	ggplot(
		aes(x = factor(condition), y = new_y, fill = stat(y > 170)) 
	) +
	stat_eye(side = "right") +
	geom_hline(yintercept = 170, linetype = "dashed", size = 2,
			   color = "red") +
	scale_fill_manual(values = c("gray80", "skyblue"))
```

## 使用brms
```{r}
b4.3 <-
  brm(
    data = d2,
    family = gaussian,
    height ~ 1 + weight,
    prior = c(
      prior(normal(178, 100), class = Intercept),
      prior(normal(0, 10), class = b),
      prior(uniform(0, 50), class = sigma)
    ),
    iter = 41000, warmup = 40000, chains = 4, cores = 4,
    seed = 4,
    file = "fits/b04.03"
  )
```


### 后验概率
```{r}
plot(b4.3)
```


```{r}
summary(b4.3)
```


```{r}
posterior_samples(b4.3) %>% as_tibble()
```



```{r, eval=FALSE}
names(b4.3)
b4.3$prior


brms::posterior_summary(b4.3)
brms::posterior_summary(b4.3) %>% as.data.frame() %>% rownames_to_column()
brms::posterior_samples(b4.3) %>% as_tibble()
brms::posterior_samples(b4.3, add_chain = T) %>% as_tibble()

# same as 
tidybayes::get_variables(b4.3)
tidybayes::spread_draws(b4.3, b_Intercept, b_weight, sigma, lp__)
```

## 预测

### 单个值

```{r}
tb <- tibble(
  weight = 50
)
```

```{r}
post <- tibble(
  pred_height = predict(b4.3, newdata = tb, summary = FALSE)
)
post
```



```{r}
p_cut <- mean(post$pred_height > 150)
p_cut
```


```{r}
library(tidybayes)
# https://cran.r-project.org/web/packages/tidybayes/vignettes/tidybayes.html
post %>%
  ggplot(aes(x = pred_height, y = 0, fill = stat(x > 150))) +
  stat_halfeyeh() +
  geom_vline(
    xintercept = 150, linetype = "dashed", size = 2,
    color = "red"
  ) +
  scale_fill_manual(values = c("gray80", "skyblue")) +
  annotate(
    geom = "label", x = 160, y = 0.25, label = p_cut
  )
```


### 多个值
```{r}
tb <- tibble(
	weight = c(64, 68, 72)
)

```



```{r}
post <-
  predict(b4.3, newdata = tb, summary = FALSE) %>%
  as_tibble() %>%
  set_names(c(64, 68, 72)) %>%
  mutate(iter = 1:n())
post
```


```{r}
prob_cut <- post %>%
  summarise(
    at_64 = mean(`64` >= 170),
    at_68 = mean(`68` >= 170),
    at_72 = mean(`72` >= 170)
  )
prob_cut
```


```{r}
post_longer <- post %>%
  pivot_longer(
    cols = -iter,
    names_to = "weight",
    values_to = "height"
  ) %>%
  mutate(weight = as.numeric(weight))

post_longer
```



```{r}
post_longer %>%
  ggplot(aes(x = height, y = factor(weight), fill = stat(x > 170))) +
  stat_halfeyeh() +
  geom_vline(
    xintercept = 170, linetype = "dashed", size = 2,
    color = "red"
  ) +
  scale_fill_manual(values = c("gray80", "skyblue")) +
  annotate(geom = "label", x = 160, y = 1.4, label = prob_cut$at_50) +
  annotate(geom = "label", x = 160, y = 2.4, label = prob_cut$at_51) +
  annotate(geom = "label", x = 160, y = 3.4, label = prob_cut$at_52)
```


### add_predicted_draws
```{r}
# 这里的add_predicted_draws  = predict() + as_tibble() + pivot_longer()
post_draw <- tb %>% add_predicted_draws(b4.3) 
post_draw
```


```{r}
prob_pred <- post_draw %>% 
	group_by(weight) %>% 
	summarise(
	 pred_height_mean = mean(.prediction),
	 prob_above_line = mean(.prediction >= 170)
	)
prob_pred
```


```{r}
# normal style
post_draw %>% 
	ggplot(aes(x = .prediction, y = factor(weight), fill = stat(x > 170))) +
	stat_halfeyeh() +
	geom_vline(xintercept = 170, linetype = "dashed", size = 2,
			   color = "red") +
	scale_fill_manual(values = c("gray80", "skyblue")) +
	scale_x_continuous(limits = c(150, 200))
```


```{r}
# flip
post_draw %>% 
	ggplot(aes(x = .prediction, y = factor(weight), fill = stat(x > 170))) +
	stat_halfeyeh() +
	geom_vline(xintercept = 170, linetype = "dashed", size = 2,
			   color = "red") +
	scale_fill_manual(values = c("gray80", "skyblue")) +
	coord_flip()
```


```{r}
# best
post_draw %>% 
	ggplot(
		aes(x = factor(weight), y = .prediction, fill = stat(y > 170)) 
		) +
   	stat_eye(side = "right") +
	geom_hline(yintercept = 170, linetype = "dashed", size = 2,
			   color = "red") +
	scale_fill_manual(values = c("gray80", "skyblue"))
```


```{r, fig.asp= 0.816}
# plot original data and predict data together
library(ggforce)
# https://davidsmale.netlify.com/portfolio/soviet-space-dogs-part-2/
desc <- '未来三年进入双一流学科的概率'

post_draw %>% 
	ggplot(
		aes(x = weight, y = .prediction, fill = stat(y > 170)) 
	) +
	stat_eye(side = "right") +
	geom_point(data = d2, aes(x = weight, y = height)) +
	geom_hline(yintercept = 170, linetype = "dashed", size = 2,
			   color = "red") +
	scale_fill_manual(values = c("gray80", "skyblue")) +
	annotate("text", x = 35, y = 170 - 2, 
			 label = "进入双一流学科的阈值线", size = 4, color = "red") +
	geom_mark_ellipse(aes(x = 65, y = 190, 
					   label = '贝叶斯预测', description = desc),
					  #label.family = "Space Mono",
					  label.fontsize = 11,
					  label.colour = c("#CC79A7", "black"),
					  label.fill = NA,
					  label.buffer = unit(1, 'mm'), #间距
					  colour = NA,
					  fill = NA) +
	geom_text(data = prob_pred, aes(x = weight + 2, 
									y = pred_height_mean, 
									label = scales::percent(prob_above_line))) +
	theme_bw() +
	theme(legend.position = "none") +
	labs(title = "物理学科未来三年进入双一流学科的概率",
		 subtitle = "基于引文量的贝叶斯预测",
		 x = "时间（年）",
		 y = "被引量")
```

